name:                haskell-json-parser
version:             1.0.0.0
license:             BSD3
author:              "Robert Bisewski"
maintainer:          "contact@ibiscybernetics.com"
copyright:           "2022 Robert Bisewski"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  haskell-json-parser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-json-parser
    - containers
    - hashtables

tests:
  haskell-json-parser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-json-parser
